apiVersion: batch/v1
kind: Job
metadata:
  name: redisloader 
spec:
#  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: loader 
        image: lanceatro/wowza:v0.0.1
        command: ["ruby","app/job.rb"]
        imagePullPolicy: Always 
        env:
          - name: REDIS_HOST
            value: 'redis-primary'
          - name: REDIS_PORT
            value: '6379'
      restartPolicy: Never
